line-length = 100
target-version = "py313"

[lint]
select = [
    "A",
    "ANN",
    "BLE",
    "E",
    "F",
    "B",
    "I",
    "N",
    "UP",
    "YTT",
    "FLY",
]
ignore = [
    'N812',
    'ANN401',
]
