name: Python CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PACKAGE_MANAGER: 'micromamba'
      PYTHONPATH: '.'
    steps:
    - uses: actions/checkout@v4
    - uses: mamba-org/setup-micromamba@v1
      with:
        environment-name: ci
        create-args: -c conda-forge -c pytorch --channel-priority strict --file requirements_conda.txt --yes
        init-shell: bash
        cache-environment: true
        post-cleanup: 'none'
    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_pip.txt
      shell: micromamba-shell {0}
    - name: ruff
      run: |
        ruff format --check .
        ruff check .
      shell: micromamba-shell {0}
    - name: pytest
      run: |
        pytest -vx test
      shell: micromamba-shell {0}
